### ISSUE TITLE
java.io.IOException:Connection reset by peer

### ISSUE THREAD

**Issue by Raffiki** [apsaltis/nifi-gettcp-bundle#3]
Above exception is thrown at https://github.com/apsaltis/nifi-gettcp-bundle/blob/master/nifi-gettcp-processors/src/main/java/org/apache/nifi/processors/gettcp/GetTCP.java#L617 when the TCP server is restarted.

Is there any way to handle such cases with the current processor or does this need to be developed?

**Comment by Raffiki** [comment]
I made a first draft of the processor which survives connections resets. I usedNetty to handle the connections.
Would love to have some feedback if there's time.

https://github.com/IxorTalk/nifi-gettcp-bundle/tree/raf/netty-tcp-client

**Comment by ddewaele** [comment]
@apsaltis : Any updates on this ? Seems that there are still some issues with the TCP reconnect.
Is there a roadmap for this processor (and plans to include it in the standard nifi distribution) ?

**Comment by apsaltis** [comment]
@ddewaele The JIRA for this processor and the documented ideas are here: [https://issues.apache.org/jira/browse/NIFI-2615](url)

@Raffiki - Sorry for not looking at this sooner. Using netty is certainly an interesting idea. This processor is going to be going through some refactoring/redesign before being included in the NiFi distribution.
