### ISSUE TITLE
Bring code in synch with NIFI-2615 

### ISSUE THREAD

**Issue by apsaltis** [apsaltis/nifi-gettcp-bundle#8]
@ddewaele @Raffiki -- The code here is now in-sync with NIFI-2615, which is also in my NIFI branch -- [https://github.com/apsaltis/nifi/tree/NIFI-2615](url)

**Comment by ddewaele** [comment]
@apsaltis  : I can't see the NIFI-2615 branch. 

Are you continuing the development on master ?

We would need a GetTCP connector with reconnect functionality relatively soon. I was holding out for your refactoring / Nifi PR as I would prefer an "official" NiFi component.

I noticed that you are a Hortonworks employee ? Is it possible to provide a roadmap / timeline / estimate on the GetTCP processor :)

**Comment by apsaltis** [comment]
@ddewaele --Sorry I gave you the wrong path to the NIFI-2615 branch, it is in my fork of the Apache NiFi repo -- https://github.com/apsaltis/nifi/tree/NIFI-2615

I am developing in that branch.

I am happy to make the changes needed to make it work for your use case.

You are correct, I am a Hortonworks employe. There is no official timeline for the GetTCP processor, I had submitted a P/R about a month ago and there was a dialog on that. However, at the time there was discussion of refactoring it and once it meets the community needs and abides by best practices then it would be accepted. As far as roadmap, that is all tracked in this JIRA (https://issues.apache.org/jira/browse/NIFI-2615)

**Comment by ddewaele** [comment]
Hi @apsaltis,

I've updated the NiFi mailinglist with some info on the progress of our netty4 based GetTCP processor.

would be interested in your take on this and see if we would be able to join forces in getting this released.

We have lots of practical use cases for this.

**Comment by apsaltis** [comment]
Hi @ddewaele ,
Sorry for my delay in getting back to you. Was away from the keyboard for a while over the holidays. I'm totally open and would love to see the netty4 implementation you are using. Currently the processor is being refactored / re-designed a bit to better meet NiFi best practices.
